apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: personal-website
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ulyssetsd/ulyssetsd.github.io
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: personal-website
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: personal-website
  path: "./k8s"
  prune: true
  wait: true
