# IT-Tools - Collection of handy developer utilities
# https://github.com/CorentinTh/it-tools
apiVersion: v1
kind: Namespace
metadata:
  name: it-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
      - name: it-tools
        image: corentinth/it-tools:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: it-tools
spec:
  selector:
    app: it-tools
  ports:
  - port: 80
    targetPort: http
    name: http
---
# Middleware for VPN-only access
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: vpn-only
  namespace: it-tools
spec:
  ipAllowList:
    sourceRange:
      - 10.8.0.0/24
      - 192.168.1.0/24
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: it-tools-tls
  namespace: it-tools
spec:
  secretName: it-tools-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - it-tools.ulyssetassidis.fr
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: it-tools
  namespace: it-tools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`it-tools.ulyssetassidis.fr`)
      kind: Rule
      middlewares:
        - name: vpn-only
      services:
        - name: it-tools
          port: 80
  tls:
    secretName: it-tools-tls
