apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pi-grafana
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ulyssetsd/pi-grafana
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pi-grafana
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: pi-grafana
  path: "./k8s"
  prune: true
  wait: true
---
# Traefik Middleware to restrict access to local network and VPN
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local-network-only
  namespace: monitoring
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.0/24    # Local WiFi network
      - 10.8.0.0/24       # WireGuard VPN range
      - 10.42.0.0/16      # Kubernetes pod network
      - 10.43.0.0/16      # Kubernetes service network
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-local-network-only@kubernetescrd
spec:
  tls:
  - hosts:
    - grafana.ulyssetassidis.fr
    secretName: grafana-tls
  rules:
  - host: grafana.ulyssetassidis.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
