---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mojo2600
  namespace: flux-system
spec:
  interval: 1h
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
# NOTE: Create the password secret manually for security:
# kubectl create secret generic pihole-admin-password \
#   --from-literal=password='YourSecurePasswordHere' \
#   --namespace=pihole
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: '2.34.0'
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 1m
  values:
    # Use latest stable Pi-hole image (Docker: 2025.08.0 = Core: v6.1.4)
    image:
      tag: '2025.08.0'
    
    # Use existing secret for admin password
    admin:
      existingSecret: "pihole-admin-password"
      passwordKey: "password"
    
    # Configure upstream DNS servers (Cloudflare)
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    
    # Enable persistent storage
    persistentVolumeClaim:
      enabled: true
      size: "1Gi"
      annotations: {}
    
    # Configure DNS service with LoadBalancer
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: "192.168.1.153"  # Use an unused IP in your network range
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      externalTrafficPolicy: Local
      
    # Configure web interface service  
    serviceWeb:
      type: ClusterIP
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
        
    # Configure ingress for web interface
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - pihole.ulyssetassidis.fr
      tls:
        - secretName: pihole-tls
          hosts:
            - pihole.ulyssetassidis.fr
    
    # Pod DNS configuration
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 1.1.1.1
    
    # Custom DNS entries for your local network
    dnsmasq:
      customDnsEntries:
        - address=/raspberrypi.local/192.168.1.150
        - address=/pi.local/192.168.1.150
        - address=/wg-easy.local/192.168.1.150
        - address=/portainer.local/192.168.1.150
      
      # Additional hosts entries
      additionalHostsEntries:
        - 192.168.1.150 raspberrypi.local
        - 192.168.1.150 pi.local
        - 192.168.1.150 k3s.local
    
    # Resource limits
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 100m
    
    # Health probes
    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 10
        timeoutSeconds: 5
      readiness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 10
        timeoutSeconds: 5
