# Stirling-PDF - Self-hosted PDF manipulation tool
# https://github.com/Stirling-Tools/Stirling-PDF
apiVersion: v1
kind: Namespace
metadata:
  name: stirling-pdf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  labels:
    app: stirling-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
      - name: stirling-pdf
        image: frooodle/s-pdf:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DOCKER_ENABLE_SECURITY
          value: "false"
        - name: SECURITY_ENABLELOGIN
          value: "false"
        - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
          value: "false"
        - name: LANGS
          value: "en_GB,fr_FR"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        # Stirling-PDF takes a long time to start (LibreOffice, etc.)
        startupProbe:
          httpGet:
            path: /api/v1/info/status
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /api/v1/info/status
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/info/status
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  selector:
    app: stirling-pdf
  ports:
  - port: 80
    targetPort: http
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: default-vpn-only@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - pdf.ulyssetassidis.fr
    secretName: stirling-pdf-tls
  rules:
  - host: pdf.ulyssetassidis.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stirling-pdf
            port:
              number: 80
