apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: website
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/ulyssetsd/ulyssetsd.github.io
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: website
  namespace: flux-system
spec:
  interval: 1m
  path: "./k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: website
  targetNamespace: website
