apiVersion: v1
kind: Namespace
metadata:
  name: wg-easy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-config
  namespace: wg-easy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  namespace: wg-easy
  labels:
    app: wg-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-easy
  template:
    metadata:
      labels:
        app: wg-easy
    spec:
      containers:
      - name: wg-easy
        image: ghcr.io/wg-easy/wg-easy:15
        ports:
        - containerPort: 51820
          protocol: UDP
          name: wireguard
        - containerPort: 51821
          protocol: TCP
          name: web
        env:
        - name: INSECURE
          value: "false"
        volumeMounts:
        - name: wg-config
          mountPath: /etc/wireguard
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
      volumes:
      - name: wg-config
        persistentVolumeClaim:
          claimName: wg-easy-config
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy-web
  namespace: wg-easy
spec:
  selector:
    app: wg-easy
  ports:
  - port: 51821
    targetPort: 51821
    name: web
---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy-vpn
  namespace: wg-easy
spec:
  type: LoadBalancer
  selector:
    app: wg-easy
  ports:
  - port: 51820
    targetPort: 51820
    protocol: UDP
    name: wireguard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wg-easy
  namespace: wg-easy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - wg-easy.ulyssetassidis.fr
    secretName: wg-easy-tls
  rules:
  - host: wg-easy.ulyssetassidis.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wg-easy-web
            port:
              number: 51821
