apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eclosion
resources:
  - resources.yaml
configMapGenerator:
  - name: eclosion-content
    files:
      - index.html
      - default.conf
