name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: my-app
  # Registry domain will be constructed from REGISTRY_DOMAIN secret
  # Format: registry.{domain}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Private Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_DOMAIN }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        build-args: |
          GIT_COMMIT=${{ github.sha }}
          VERSION=${{ github.run_number }}
        tags: |
          ${{ secrets.REGISTRY_DOMAIN }}/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.REGISTRY_DOMAIN }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deployment Summary
      run: |
        echo "🚀 Deployment Complete!"
        echo "📦 Image pushed to: ${{ secrets.REGISTRY_DOMAIN }}/${{ env.IMAGE_NAME }}:latest"
        echo "🏷️  Tagged as: ${{ env.REGISTRY_DOMAIN }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        echo "⏱️  Watchtower will automatically pull and deploy within 5 minutes"
        echo "🔍 Monitor deployment: https://portainer.ulyssetassidis.fr"
